### ISSUE TITLE
Android app does not work - parse error

### ISSUE THREAD

**Issue by hopo28** [CITCEuraRFID/KeyDuino#3] opened 2016-07-05 09:53 UTC
error that comes up:
Parse Error
There was a problem while parsing the package.

phones tested on:
Samsung galaxy S7 running android 6.0.1
Samsung galaxy S5 running android 6.0.1
Samsung galaxy S3 running android 4.3
Samsung galaxy S2 running android 4.1.2

**Comment by RayBor** [comment] 2016-07-05 10:24
Hi, and thanks for your review.
Could you please be more specific ?
When does exactly this error message appears ?
Thanks

**Comment by hopo28** [comment] 2016-07-05 10:28
Its when i try to install it.
In all cases i made sure that the unknown sources thing was allowed in the
accessibility settings, so its not that :-/

**Comment by RayBor** [comment] 2016-07-05 10:35
Plus it tells exactly the problem when it's about unknown sources.

It is quite strange because I can install the app through the APK myself on my Sony Xperia, and it works too on Nexus tablets. Did you try to download the apk again ? Maybe there was a problem with it ...

There are a few sources on the Internet that pretends to know how to solve this problem ...
Check this one : http://www.smarttricks.net/fix-there-is-a-problem-parsing-the-package

Tell me if it works :)

**Comment by hopo28** [comment] 2016-07-05 10:54
yup, tried re-downloading, same error, double checked the unknown sources
thing (under security in marshmallow)

right, done some searching, and there are 4 things that keep coming up;

1-install apps from unknown sources - checked that

2-corrupt apk - downloaded several times so its not that unless the one on
github is corrupt

3-not compatable with my device(s) - possible i suppose, im guessing we
have no proof of it working on an S2,S3,S5,S7 so far?

4-something is incorrect in the manifest - i dont really understand this
but guessing its like a header in the APK, either way, that bit is out of
my control

I'm out of ideas for now.

**Comment by RayBor** [comment] 2016-07-05 13:00
Well, I just downloaded the Apk from GitHub, sent it to a Galaxy S5 and had no problem installing it.
So I have no more ideas either :/

But anyway, the app isn't that great ... maybe the world doesn't want you to use that dirt :p 
May I know what you need it for ?

**Comment by hopo28** [comment] 2016-07-05 13:10
I was planning on creating a project similar to the demo one; the infinity
coffee table and was looking into using a phone as an interface,
admittedly, i havent taken the keyduino out of the box yet, but was looking
into the app first.

ok, on a whim i replicated what you did... downloaded the apk, then sent to
the phone as oppposed to downloading on the phone itself... it now works!
I imagine there is something up with downloding on the phone.
i see what you mean about the app being a bit lacklustre, do you know of
others that might suit my requirements?

issue appers to be a non-issue :-/

**Comment by RayBor** [comment] 2016-07-05 13:28
Then I close it :)

If you want something like the NFC Infinity Table, the KeyDuino app should be enough. But you can also use NXP Chameleon (like in the video) which is lighter.

In any case, this uses Peer-to-peer NFC between the devices, and we seem to have problem with a lot of phones on that. It may be a hardware problem (KeyDuino uses a PN532, and maybe it wants something like it).

So if it's not working with it (AKA you can begin the NFC P2P communication but never finish it) your phone is not compatible.
I don't have a lot of time to work on that and see if the problem is within the library, but I'll keep you posted if any news.

Thanks again for your review, and don't hesitate if you need anything else ;)

Ray

**Closed by RayBor** 2016-07-05 13:28 UTC
